# -*- coding: utf-8 -*-
"""Model_Development.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Y6UYFTMq9B3cm2U8-PjcMMZdJFXQhrg
"""

import pandas as pd

data = pd.read_pickle('/content/drive/MyDrive/artifact/transformed_data.pkl')

data.head()

data.info()

from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RandomizedSearchCV

xgbclfr = XGBClassifier(random_state=42)

param_grid={
    'n_estimators':[100, 200, 300],
    'max_depth':[1, 2, 3, 4, 5],
    'min_child_weight':[1, 2, 3, 4, 5],
    'gamma':[0.1, 0.2, 0.3, 0.4, 0.5],
    'learning_rate':[0.01,0.1,1,1.5]
}
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [1, 2, 3, 4, 5],
    'min_child_weight': [1, 2, 3, 4, 5],
    'gamma': [0.1, 0.2, 0.3, 0.4, 0.5],
    'learning_rate': [0.01, 0.1, 1, 1.5]
}

x,y=data.drop('FraudResult',axis=1),data['FraudResult']
randomizedsearch = RandomizedSearchCV(estimator=xgbclfr,param_distributions=param_grid,scoring='f1')
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
randomizedsearch.fit(x_train,y_train)
print(randomizedsearch.best_estimator_)
print(randomizedsearch.best_params_)

import pickle
with open('model.pkl', 'wb') as files:
    pickle.dump(randomizedsearch.best_estimator_, files)

